### ISSUE TITLE
Maintenance

### ISSUE THREAD

**Issue by fschulze** [fschulze/sqlalchemy_schemadisplay#36]
Who would like to take over maintenance of this project? I don't have the interest and time to do it anymore.

**Comment by bkt92** [comment]
Hello, I like to help with maintaining this project.

**Comment by fschulze** [comment]
Thanks for the offer. I'm looking for someone who takes over maintainership from me. Maybe your offer in helping will convince someone to do so.

**Comment by nhoening** [comment]
I read in other PRs that @abitrolly and @RagingRoosevelt are/were also interested. Pinging them here.

**Comment by RagingRoosevelt** [comment]
I'm willing although I think it would be healthy if there were more than one person.  I'm not sure what specifically would be necessary but I assume it would require:
* setting up an org on github to transfer ownership to
* setting up organization-managed access to publish to pypi

I have some ideas I've been working on that would allow it to be a bit more modular such as outputting a JSON object with the structure from SQLAlchemy, but that's a topic for a different thread.

**Comment by fschulze** [comment]
This might be a good replacement: https://github.com/tedivm/paracelsus

**Comment by Zlopez** [comment]
I can take this over together with @RagingRoosevelt, I already have some idea on setting up CI using github actions and I'm already maintaining https://github.com/fedora-infra/anitya which is using this project as dependency

**Comment by fschulze** [comment]
I sent both of you invites. I would suggest taking a look at https://til.simonwillison.net/pypi/pypi-releases-from-github for releases. Let me know if you want to go that route and I will set up the PyPI side. I will gradually increase permissions and eventually transfer the repo to you.

**Comment by Zlopez** [comment]
@fschulze Thanks. I quickly looked at the link you sent and it seems to be a good option for us. At least we don't need to care about PyPI side and just care about the github itself :-)

**Comment by Zlopez** [comment]
Today I wanted to look at implementing CI, so the people creating PR's have some feedback. I found out that there is already [GitHub action](https://github.com/fschulze/sqlalchemy_schemadisplay/blob/master/.github/workflows/test-and-release.yml) specified for that. Does it work, was it ever used?

**Comment by Zlopez** [comment]
I also tried to run the tox tests locally and plenty of them are failing. I will start looking at the existing PRs as well, maybe there are some that will fix the errors.

**Comment by abitrolly** [comment]
@Zlopez actions work. Like in fork - https://github.com/abitrolly/schemadisplay/actions/runs/7684724341/job/20941557651 It is probably that there were no commits to trigger them since they've been added.

**Comment by abitrolly** [comment]
@Zlopez https://github.com/fschulze/sqlalchemy_schemadisplay/pull/40 CI/CD works in this repo too.

**Comment by abitrolly** [comment]
Ok. I fixed running tests for Python 2 by using Python 2 docker image https://github.com/fschulze/sqlalchemy_schemadisplay/pull/40 

The Python 3 version doesn't work. I guess that's why we are here.

**Comment by abitrolly** [comment]
Python 3 tests work now by limiting the SQLAlchemy < 2.

It would be nice to release 1.4 of `sqlalchemy_schemadisplay` as the last version to support Python 2, and switch to the next major version for Python 3.

**Comment by Zlopez** [comment]
@abitrolly Trying to work on that. First I need to get some of the PRs merged.

**Comment by Zlopez** [comment]
Today I merged https://github.com/fschulze/sqlalchemy_schemadisplay/pull/35 which should fix the issue with SQLAlchemy 2 and it improves the structure of project.

**Comment by Zlopez** [comment]
Went through all the PRs and I think the sqlalchemy_schemadisplay is ready for next release. @fschulze Do you have any official way of doing releases?

**Comment by Zlopez** [comment]
I found this action https://github.com/fschulze/sqlalchemy_schemadisplay/blob/master/.github/workflows/cd.yml, it will work as it is setup now?

**Comment by fschulze** [comment]
I think I tested it with test.pypi.org, but I would have to setup tokens for pypi.org. Do you want to have a release with the current state, or would you want to look into https://til.simonwillison.net/pypi/pypi-releases-from-github first? I could also look into doing a manual release.

**Comment by abitrolly** [comment]
> Today I merged https://github.com/fschulze/sqlalchemy_schemadisplay/pull/35 which should fix the issue with SQLAlchemy 2 and it improves the structure of project.

I don't think it is a good idea to introduce new feature without a maintenance 1.4 release for Python 2.x first.

DB schema tool should work on ancient Python versions first to help people with upgrading.

**Comment by Zlopez** [comment]
@abitrolly That still works with 1.3, you just need to stay on SQLAlchemy < 2.

I'm currently tempted to release 2.0 and skip 1.4 as the current state has plenty of changes or tag as 1.4 the commit before the SQLAlchemy 2.X support. What do you think?

@fschulze The solution in CD is using https://github.com/pypa/gh-action-pypi-publish, which looks like a healthy project. So I'm OK with using that.

**Comment by abitrolly** [comment]
@Zlopez I think the proper way is to branch 1.x off https://github.com/fschulze/sqlalchemy_schemadisplay/pull/40 make 1.4 release for Python 2, and then do release from main branch for Python 3 users.

**Comment by Zlopez** [comment]
The only change in #40 is actually limiting the sqlalchemy version < 2. Which is easy to do. I can create a 1.4 branch and add this change to it and release a 1.4 version from it.

Let me check if I can actually do that with master, adding one commit between two others and release that as 1.4.

**Comment by abitrolly** [comment]
@Zlopez that's not the only change. #40 fixes the whole CI/CD pipeline for Python 2.

**Comment by Zlopez** [comment]
Let me check what I can do with that.

**Comment by Zlopez** [comment]
@abitrolly Created https://github.com/fschulze/sqlalchemy_schemadisplay/tree/1.x and included your changes, but the github action is failing. Feel free to look at that (I just added sudo to apt-get). After that I will update the README and tag the 1.4 version for release.

The master is now coming forward version 2.0. :-)

**Comment by abitrolly** [comment]
@Zlopez why you don't want to merge my PR? It has all commits well explained - https://github.com/fschulze/sqlalchemy_schemadisplay/pull/40/commits and specifically https://github.com/fschulze/sqlalchemy_schemadisplay/pull/40/commits/c85f626014ea007fe2a1aabae75dc1c858d98892 It also gives me some sweet credits. :D

**Comment by Zlopez** [comment]
@abitrolly Because it's opened against master and now has plenty of conflicts after #35 was merged. If you open it up against 1.x branch I can merge that.

**Comment by abitrolly** [comment]
@Zlopez that should do it without conflicts.

```sh
git branch -D 1.x
git fetch origin pull/40/head:1.x
git switch 1.x
git push -f origin 1.x
```

From https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally

**Comment by Zlopez** [comment]
@abitrolly No need to do it now as I copied out all the changes in your PR, because it was easier to just type them out. But if you want you can still check the [failing action](https://github.com/fschulze/sqlalchemy_schemadisplay/actions/runs/7699592790) and produce a fix for it.

**Comment by abitrolly** [comment]
@Zlopez I am very defensive of my authorship in open source projects, because I am not being paid for it, so I am not okay when somebody just copies my commits. I admit my brain is somewhat damaged. :D

**Comment by Zlopez** [comment]
@abitrolly I added you as author to all the new commits in 1.x branch. And you are now responsible to fix the failing github action :-D

**Comment by abitrolly** [comment]
@Zlopez I can not push here.
```
ERROR: Permission to fschulze/sqlalchemy_schemadisplay.git denied to abitrolly.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists. 
```

I don't know what's wrong here. Just force push green https://github.com/abitrolly/schemadisplay/tree/1.x and it's finished.

**Comment by Zlopez** [comment]
@abitrolly You should still be able to create PRs against 1.x branch.

**Comment by abitrolly** [comment]
@Zlopez I am tired.

**Comment by abitrolly** [comment]
@Zlopez if you remove the commits from the branch, I can push it, but dealing with the merge conflicts I don't want.

**Comment by Zlopez** [comment]
@abitrolly The commits are now removed from 1.x branch, have fun.

**Comment by Zlopez** [comment]
@fschulze I prepared a [PR](https://github.com/fschulze/sqlalchemy_schemadisplay/pull/42) for 2.0 release. Could you check if everything looks OK? If everything is OK I can merge that and add the tag and hopefully the CD will release that on PyPI.

**Comment by abitrolly** [comment]
> @abitrolly The commits are now removed from 1.x branch, have fun.

Push didn't work, so here is the PR #43.
```
✗ git push -v -u origin 1.x
Pushing to github.com:fschulze/sqlalchemy_schemadisplay.git
ERROR: Permission to fschulze/sqlalchemy_schemadisplay.git denied to abitrolly.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by Zlopez** [comment]
@abitrolly That is correct, you don't have direct push permissions for the main repository. I already looked at the PR and it's LGTM, but you should remove the close of #33 as this will be properly fixed in release 2.0.

**Comment by Zlopez** [comment]
@abitrolly Here is the [PR](https://github.com/fschulze/sqlalchemy_schemadisplay/pull/44) for 1.4 release, I would like to wait for @fschulze to review and add correct token to let us publish directly on PyPI.

**Comment by fschulze** [comment]
I only took a rough look, as the point is to pass maintenance over. You can merge yourself and do the tag. I will then take the resulting files from test.pypi.org after you verified it is all good and upload them to pypi.org. I don't want to mess with the token stuff right now.

**Comment by Zlopez** [comment]
@fschulze Thanks, let me get to it. I will first do the 1.4 version and then continue with 2.0.

**Comment by fschulze** [comment]
Should I publish them right away, or do you want to do some quick install checks first?

**Comment by Zlopez** [comment]
I did tested that before, so we can publish it right away.

**Comment by Zlopez** [comment]
I'm currently working on 2.0, there is some issue with CD github task, but I know what happened.

**Comment by fschulze** [comment]
I uploaded 1.4 to pypi.org.

I also removed the 2.0 tag. You should be able to recreate and push it now.

**Comment by Zlopez** [comment]
Thanks. Let me push it again.

**Comment by Zlopez** [comment]
The 2.0 is now available on test.pypi.org https://test.pypi.org/project/sqlalchemy-schemadisplay/

**Comment by Zlopez** [comment]
@fschulze Feel free to move it to pypi.org

**Comment by fschulze** [comment]
done

**Comment by Zlopez** [comment]
Thanks, I think we can close this issue then. I will go over other issues and see if they could be closed as well :-)
